language: csharp
mono: none
dotnet: 3.1.405
solution: TravisCI.sln
branches:
  only:
  - master
install:
  - nuget restore TravisCI.sln
script:
  - dotnet restore
  - msbuild /p:Configuration=Release TravisCI.sln
